on:
    push:
        branches:
            - master

name: CI

jobs:
    update-revision-file:
        name: REVISION

        runs-on: ubuntu-latest

        steps:
            - name: "Checkout"
              uses: actions/checkout@v1.2.0
              with:
                ref: master

            - name: "Update REVISION file"
              run: echo $(git describe --always --long) > REVISION

            - name: "Commit REVISION file"
              uses: stefanzweifel/git-auto-commit-action@v2.5.0
              with:
                  branch: master
                  commit_message: "Update REVISION file"
                  file_pattern: REVISION
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
